@startuml
left to right direction
actor "Course Instructor" as CI
actor "Student" as S
usecase "Review aggregated feedback" as UC1
usecase "Submit anonymous course feedback" as UC2
CI --> UC1
S --> UC2
@enduml